baseURL: http://example.org/
languageCode: en-au
title: My New Hugo Site
# alternate copyright company text
copyright: Web Design Inc.
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 85
  resampleFilter: Box

params:
  image:
    widths: [600, 900, 1300]
    # densities: [1,2]
    class: img-fluid